version: "2"

run:
  timeout: 5m

linters:
  enable:
    - contextcheck
    - durationcheck
    - errcheck
    - errorlint
    - fatcontext
    - gci
    - ginkgolinter
    - gocritic
    - gofumpt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nonamedreturns
    - noctx
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - wastedassign

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/openshift)
  errcheck:
    check-type-assertions: true
  gosec:
    excludes:
      - G115
  errorlint:
    errorf: true
    asserts: true
    comparison: true
  govet:
    enable-all: true
    disable:
      - fieldalignment

issues:
  exclude-rules:
    - linters:
        - revive
      text: "don't use ALL_CAPS in Go names; use CamelCase"
    - linters:
        - revive
      text: " and that stutters;"
    - path: '(.+)_test\.go'
      text: "dot-imports: should not use dot imports"
    - path: '(.+)_test\.go'
      linters:
        - errcheck
        - gosec
